common/res/defaults.json

@Posteo [integrated the API of Mailevelope](https://posteo.de/en/blog/new-posteo-webmail-interface-can-find-public-keys) ([German version](https://posteo.de/blog/neu-posteo-webmailer-findet-schl%C3%BCssel-automatisch)). Therefore it can be activated by default.

Activate API for Posteo

---

src/app/app.js

Update visible copyright year to 2018 because there were lots of changes done in 2018 and it looks as modern as it should not first sight.

Update copyright year to 2018

---

src/modules/key.js

Previously User Attributese (such as photos, but not limited to them) would trigger an error because `user.userId` attribute is `null` in that case (`user.userAttribute` property would be set).
The fix checks if an `userId` property is set before using it effectively omitting User Attributes.
See: https://openpgpjs.org/openpgpjs/doc/key.js.html#line800

Fix filtering User IDs

---

package-lock.json
package.json
src/lib/autolink.js
src/lib/lib-mvelo.js
src/modules/mime.js
test/karma.conf.js
test/lib/lib-mvelo-test.js

Add html link tag to URLs and email addresses to make them clickable inside decrypted message container.
**Added dependency**
linkifyjs (https://github.com/SoapBox/linkifyjs)
**Added files**
src/lib/autolink.js
test/lib/lib-mvelo-test.js
**Modified files**
src/lib/lib-mvelo.js
src/modules/mime.js

Add clickable links and emails to decrypted message

---

locales/de/messages.json
locales/en/messages.json

See: https://github.com/mailvelope/mailvelope/issues/647
`alert_invalid_domainmatchpattern_warning` fixed for en and de

[#647] Fixing alert_invalid_domainmatchpattern_warning

---

config/webpack.api.js

Running grunt triggers an error for me:
```
ERROR in Entry module not found: Error: Can't resolve './src/client-api/main.js' in '/home/azul/code/mailvelope'
```
it should be client-API not client-api in the webpack config.

fix: webpack api had wrong path

---

Gruntfile.js

taken from https://stackoverflow.com/a/52006112.
This way grunt eslint will not fix by default
but the "--fix" option will be handed on to eslint.

grunt: eslint --fix to fix detected warnings

---

.travis.yml

I had a broken extension build at some point and did not notice it because ci was green.
Split this commit from the autocrypt branch because it's not related.

ci: always run grunt to see if extension build works

---

.travis.yml

this was an after_success hook before.
after_success hooks will run after every successful task.
So if grunt succeeded but test failed grunt would still deploy the nightly.
Move the deploy-nightly.sh call into the deploy task.
This way all tasks in the test stage (test and grunt) need to pass
before it tries to deploy.

ci: deploy-nighty as deploy task

---

.travis.yml
src/client-API/client-api.js
src/content-scripts/clientAPI.js
src/controller/api.controller.js
src/controller/app.controller.js
src/modules/autocryptWrapper.js
src/modules/key.js
test/controller/api.controller-test.js
test/fixtures/keyring.js
test/modules/autocryptWrapper-test.js
test/modules/key-test.js
test/modules/keyRegistry-test.js
test/modules/keyring-test.js

API
---
```
let keyring = mailvelope.getKeyring('Posteo').then(function(kr) { keyring = kr }, console.error)
keyring.additionalHeadersForOutgoingEmail({from: "mvactest@posteo.de"}).then(console.log, console.error)
// logs: { Autocrypt: "addr=mvactest@posteo.de;keydata=xsFNBFwYsn..." }
```
Autocrypt
---------
* Key#minifyKey to build minimal version of a key.
Create a minimal key consisting of only:
* a signing-capable primary key
* a user id
* a self signature over the user id by the primary key
* an encryption-capable subkey
* a binding signature over the subkey by the primary key
* Export stringify from autocryptWrapper
This way we do not need to access anything in Autocrypt.js directly.
Also renaming all uses of autocryptWrapper to autocrypt.
Outside of the wrapper itself we do not …

Initial take on API for injecting autocrypt headers

---

src/modules/keyring.js
test/client-API/mailvelope-client-api-test.js
test/controller/api.controller-test.js
test/fixtures/headers.js
test/karma.conf.js
test/modules/autocryptWrapper-test.js
test/modules/keyRegistry-test.js
test/modules/keyring-test.js
test/polyfills.js

Initial test for the API
API level tests allow testing the wiring in the event handling
inside the controllers and the content scripts.
It ensures that API calls actually accomplish their goals.
Polyfills and Stubs
-------------------
test/polyfills.js now includes a simple implementation of
chrome.runtime.connect and .onConnect.
The local storage is stubbed entirely so we do not have to worry
about replacing it with rewire in some contexts.
We do not recover it after the run because there is no
working local storage in the test environment anyway.
Loading mailvelope-client-api.js
--------------------------------
content-scripts/clientAPI.js will add a script tag to the head
which then tries to load the mailvelope-client-api.js
This used to result in the following warning:
WARN …

Basic Api tests

---

locales/de/messages.json
locales/en/messages.json
locales/ru/messages.json
locales/uk/messages.json
src/app/settings/General.js

This addresses #837 by just adding a hint for the user to check out the wiki page on how to setup GnuPGP properly. 
IMPORTANT: This is a Draft, since it needs more translations or another way of fixing

Add better hint when GnuPG installed but not working

---

package.json
src/app/keyring/KeyImport.js
src/app/keyring/components/AdvKeyGenOptions.js
src/app/keyring/components/DatePicker.js
src/app/keyring/components/KeyDetails.js
src/app/settings/Provider.js

During the upgrade process the following problems came up:
- the new version of `react-datepicker` uses the `date-fns` instead of the moment library for date/time functionality.
- new version uses different mechanism for i18n
In this PR we 
* migrated to `react-datepicker` v4.20 in `DatePicker` component
* made `DatePicker` consume and return `Date` instead of `moment` objects 
* adjusted parent components to convert date to and from `moment` when passing it to/from `DatePicker`.
* implemented new i8n for underlying `react-datepicker`
Closes 9Tctd3vw, 9of4k6iz

Update react-datepicker to v4.20

---

src/content-scripts/attachmentFrame.js

In the top right corner of a extract frame we display a close button. In some cases this close button is hidden by vertical scrollbars on the right side. This was not there before and looks like a style change in Gmail.
- PGP/MIME message or a message that has text content and manually a .asc file attachment
- Gmail API is active
The fix also tries to mimic the default behavior of `decryptFrame` where when in popup mode, the overlay stretches to the whole width of the message instead of fixing width and height.

Gmail ExtractFrame: scroll bar hides close button

---

src/controller/authDomain.controller.js
src/lib/inject.js

Context: Roundcube instance on non-default port: `http://localhost:8000`.
1. Trigger authorize domain dialog from Roundcube settings.
2. Dialog asks to authorize domain `*.localhost`
3. Click Confirm
4. Reload Roundcube
5. Roundcube doesn't see Mailvelope
2. Dialog asks to authorize domain `*.localhost:8000`
...
5. Roundcube sees Mailvelope
The domain auth process detects url of the tab from which it was triggered but doesn't consider port. 
Since we'd like to improve this process for the "Authorize this domain" button too, perhaps it make sense to modify "AuthDomainController#authorize" method to expect port.

Detect port in domain auth dialog

---

src/app/settings/WatchList.js
src/controller/menu.controller.js
src/lib/inject.js
src/lib/lib-mvelo.js

Context: Roundcube instance on non-default port: `http://localhost:8000`.
1. Open Mailvelope popup and click "Authorize this domain"
2. Dialog is prefilled with `*.localhost` wildcard
3. Click Confirm
4. Reload Roundcube
5. Roundcube doesn't see Mailvelope
2. Dialog is prefilled with `*.localhost:8000` wildcard
...
5. Roundcube sees Mailvelope
Closes #734

Detect port on "Auth this domain" button

---

src/app/settings/Provider.js

Adapt to the new website changes, from `/products` to `/google-workspace`

Change Mailvelope Product Page to use new GW landing

---

src/components/editor/components/RecipientInput.js

This is a fix for a regression after update to Bootstrap 4.6.2 causing issues to the RecipientInput

Bootstrap update breaks recipient input

---

src/components/editor/components/RecipientInput.js

Another bunch of fixes for regressions afrer updating `RecipientInput` to use `react-tag-input` instead of Angular component.
- `<` and `>` are replaced with `＜` and `＞` to prevent case when searching `lt` and `gt` in the HTML

`RecipientInput` regression fixes

---

package.json

Removes `ng-tags-input`. The rest of the removal has been already performed.

Remove ng-tags-input dependency

---

src/components/editor/editor.js
src/controller/editor.controller.js

- Ensure the send button only enables with a valid alternative key selection
- Reply all securly fills all recipients correctly, even if not present in keyring

Fix send button state and CC field empty on Reply All 

---

src/lib/mail-reader.js
src/modules/mime.js

Add functionality to prepend the encrypted subject line to the message. 
It alignes with [Thunderbird's](https://searchfox.org/comm-central/source/mail/extensions/openpgp/content/modules/mime.sys.mjs#203) and [Thunderbird for Android (k9)](https://github.com/thunderbird/thunderbird-android/blob/main/legacy/core/src/main/java/com/fsck/k9/mailstore/MessageViewInfoExtractor.java#L105) implementations.

Prepend encrypted subject line to messages
